### ISSUE TITLE
eq_ case sensitive?

### ISSUE THREAD

**Issue by gallarotti** [tkutcher/quickbase-client#57]
Hello,
I am running this very simple query:
```
            client_client = Client.client(TOKEN)
            client_schema = Client.schema
            q = eq_(client_schema.client_name, client_name)
            recs = client_client.query(q)
```
There is a client in the Client table called "John Davis Llc".
When I search for "JOHN DAVIS LLC" I get zero results.
When I search for "John Davis Llc" I get one result.
Is the case sensitivity introduced by "eq_" or is it already there in the "EX" Quickbase API?

FYI, the `q.where` for the first case is:
```
"{'6'.EX.'JOHN DAVIS LLC'}"
```
for the second case is:
```
"{'6'.EX.'John Davis Llc'}"
```

**Comment by tkutcher** [comment]
Hi @gallarotti - this library does not modify the value that gets passed to the quickbase API as you can see in the where string, the EX seems to enforce case sensitivity on the quickbase side of things. As far as I can tell, I don't really see anything in the API for case sensitivity. 

The only thing I can think of would be to do some "or" operators for the different cases/formats to check. Which wouldn't really be a standardized way to go about it since if you wanted to cover every case possibility you're dealing with O(2^N) or-clauses in the query string. This might be a better question for quickbase to see if they have any support for queries without case sensitivity

**Comment by gallarotti** [comment]
Thanks for confirming my gut feeling, Tim. It's weird that their API is case sensitive but the search in Quickbase itself is not. Quite a shame because it makes things so much harder...
