### ISSUE TITLE
Pydantic Data Validation?

### ISSUE THREAD

**Issue by lomnes-atlast-food** [tkutcher/quickbase-client#61]
Love the work you've done to make quick base accessible with python!  Thank you for your hard work and great tool!

**Is your feature request related to a problem? Please describe.**
I'd like to be able to perform data model validation coming to automate data quality audits from our record keeping app. In the past I've found pydantic data models to be very handy to use for this but not sure the best way to couple validation with the tool set you've built.  Our app frequently has table changes so using the cli for `qbc run model-generate` is super handy, but will overwrite any changes we make to those models directly. I'd like a recommendation from the the developers here of the approach you would take for this? **THIS IS NOT A REAL FEATURE REQUEST**

**Describe the solution you'd like**
Would be able to specify a list of data validation rules that apply at multiple levels:
* field level - a specific field in a table should have values in a specific range, or text that matches a pattern, etc.
* record level - combinations of field values should  meet some constraints (e.g. this field shouldn't be empty if some other field has a value.
* table level - e.g. identify duplicate records and flag them for review.
* app level - if a field has some value in one table there should be a value in a linked record in another table.

**Describe alternatives you've considered**
* generate models using qbc and then modify them to be pydantic models with validators, and merge changes from future qbc model-generate calls
* make a code gen wrapper to dynamically change models to a pydantic BaseModel and apply a set of validators and use those modified models
* make data integrity validation as a set of tests using a test running suite, or periodically running a separate script to test records against rules.
* use data validation via the quickbase UI, and manage the complexity of a spiderweb of rules without having a common codebase to work from.
* Add a model-update feature to the cli that allows handles updating models with schema changes without overwriting customizations to the data models.

**Additional context**
Thank you again for a brilliant tool set!

**Comment by tkutcher** [comment]
Hi there - glad the tool has been useful!

So admittedly I haven't worked much with pydantic myself, but I have a few thoughts/ideas in general which maybe could be helpful.

First - yea definitely a shortcoming that the `qbc model-generate` is mainly one-time/overwriting, ideally in the future we write something that makes this a little more re-usable for multiple runs and merging changes. I was playing around with using `typing.Annotated` properties instead of the metaclass - not sure if that would help with some of these pain-points or not, but I have to play around a little more and see if I could get that to work and if it makes sense for making models easier to maintain/work with (see thoughts in #60).

-----

> - generate models using qbc and then modify them to be pydantic models with validators, and merge changes from future qbc model-generate calls
> - make a code gen wrapper to dynamically change models to a pydantic BaseModel and apply a set of validators and use those modified models

Regarding these two approaches, I think something like the first is probably the most practical approach - I am not sure if you are doing something like this already but I was thinking it might not be too tricky to automate updating its fields. You could probably even bypass the `qbc model-generate` and just make calls directly to `get_fields_for_table`, and use the field data to update your fields in the pydantic model class.

-----

> - use data validation via the quickbase UI, and manage the complexity of a spiderweb of rules without having a common codebase to work from.

This is definitely something we can relate to. If it might be useful for you, one trick is that part of the legacy API includes setting formula fields programmatically: https://helpv2.quickbase.com/hc/en-us/articles/4418310972052-API-SetFieldProperties. See https://github.com/tkutcher/quickbase-client/blob/6be30a7d5f14906d1f6730abb6e9a958ec6535be/src/quickbase_client/client/legacy_client.py#L94-L102 for an example of calling the legacy API. But with that, you could manage formulas in a code repository and then push them out to quickbase.


----

> - Add a model-update feature to the cli that allows handles updating models with schema changes without overwriting customizations to the data models.

Yes - definitely looking to get something like this in the library at some point. Initial idea is maybe part of the code-gen API is to put some comments in to surround the area that it writes to, and then additional methods and whatnot can be preserved.
 
----

Then generally my thoughts on the use case as a whole:

> - field level - a specific field in a table should have values in a specific range, or text that matches a pattern, etc.
> - record level - combinations of field values should meet some constraints (e.g. this field shouldn't be empty if some other field has a value.
> - table level - e.g. identify duplicate records and flag them for review.
> - app level - if a field has some value in one table there should be a value in a linked record in another table.


I am not sure at the table/app level what all pydantic is able to help with - but I would think at that scope your validation rules would need to be written as some sort of quickbase query (unless you have the whole database in memory and can write validators against python data structures).


---

I understand the value of getting to be more expressive with python than you would be with the quickbase formulas/query-language, so I am happy to think through features that would make the library more useful in this regard!

Hopefully this was a little helpful or at least sparked some more ideas

**Comment by lomnes-atlast-food** [comment]
Thank you so much taking the time to give some detailed thoughts about the approaches I can take.  In the short term I may use your suggestion to define a series of tests for data validation en-bloc where I can report out on data integrity issues and help flag records that need attention for folks.

If I do play more with modifying the data models them selves I may give some thought to how to adapt the existing cli to handle comparing updated versions with new versions in a way that might be supportive for the tool.  If I do that would you be open to reviewing it as a PR? Of this there is a branch I'd be happy to contribute to it.

Thank you again!

**Comment by tkutcher** [comment]
@lomnes-atlast-food yes - certainly happy to merge any PR's! I have an old issue (#29) that is pretty much for this feature. So I would be happy to review/collaborate on that.
